# Generated by Django 5.1.3 on 2025-03-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
